# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Opstea < Formula
  desc "Multi-host SSH operations orchestrator with TUI, CLI, and SQLite audit trail"
  homepage "https://github.com/AitorDuran/opstea"
  version "0.10.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/AitorDuran/opstea/releases/download/v0.10.0/opstea_0.10.0_darwin_amd64.tar.gz"
      sha256 "e28f54456cadb256ce06c8e255a0fba99f0bfc7719d2e68f0498c29f63d8ee3b"

      define_method(:install) do
        bin.install "opstea"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/AitorDuran/opstea/releases/download/v0.10.0/opstea_0.10.0_darwin_arm64.tar.gz"
      sha256 "ac7b2d89aa5f0250984f01987cb13f989f6c4c88a959f5a897ffc6fd26543ceb"

      define_method(:install) do
        bin.install "opstea"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/AitorDuran/opstea/releases/download/v0.10.0/opstea_0.10.0_linux_amd64.tar.gz"
      sha256 "af0311f2bf109360e541c775464e503a5d8dc0d5dfadb2cece392fbb012e5092"
      define_method(:install) do
        bin.install "opstea"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/AitorDuran/opstea/releases/download/v0.10.0/opstea_0.10.0_linux_arm64.tar.gz"
      sha256 "ad2ab07cf0fa6c2968b70924fe6551690b63dfe6320ef563fd7d99a85e51e87a"
      define_method(:install) do
        bin.install "opstea"
      end
    end
  end

  test do
    system "#{bin}/opstea", "--version"
  end
end
