# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Opstea < Formula
  desc "Multi-host SSH operations orchestrator with TUI, CLI, and SQLite audit trail"
  homepage "https://github.com/AitorDuran/opstea"
  version "0.13.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/AitorDuran/opstea/releases/download/v0.13.1/opstea_0.13.1_darwin_amd64.tar.gz"
      sha256 "4b6e56e38f6522416a823b79fede76187c26099b12c4107e50c0c5684aad719b"

      define_method(:install) do
        bin.install "opstea"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/AitorDuran/opstea/releases/download/v0.13.1/opstea_0.13.1_darwin_arm64.tar.gz"
      sha256 "cf19a778263c4c9db7889baa3e6ca469f4e1355100f97cbcf4566b8090552138"

      define_method(:install) do
        bin.install "opstea"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/AitorDuran/opstea/releases/download/v0.13.1/opstea_0.13.1_linux_amd64.tar.gz"
      sha256 "08eb6b6643a99687a547640fbfd6cb389d96062b3ad39af801f7c8493da3eaaf"
      define_method(:install) do
        bin.install "opstea"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/AitorDuran/opstea/releases/download/v0.13.1/opstea_0.13.1_linux_arm64.tar.gz"
      sha256 "9c26c8721b5faa4862019dc6bc2797efad67c9b9631de394d53d6cf4d8ed8966"
      define_method(:install) do
        bin.install "opstea"
      end
    end
  end

  test do
    system "#{bin}/opstea", "--version"
  end
end
