# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Opstea < Formula
  desc "Multi-host SSH operations orchestrator with TUI, CLI, and SQLite audit trail"
  homepage "https://github.com/AitorDuran/opstea"
  version "0.5.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/AitorDuran/opstea/releases/download/v0.5.1/opstea_0.5.1_darwin_amd64.tar.gz"
      sha256 "f9375759436cb7a67952fb851f15e91b40f6b50c335c6a3e657a1de0920bd006"

      define_method(:install) do
        bin.install "opstea"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/AitorDuran/opstea/releases/download/v0.5.1/opstea_0.5.1_darwin_arm64.tar.gz"
      sha256 "86b2774912cf38753c2caef9d551bfec0a9ace2d8d920be2f143fe71cf47dc51"

      define_method(:install) do
        bin.install "opstea"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/AitorDuran/opstea/releases/download/v0.5.1/opstea_0.5.1_linux_amd64.tar.gz"
      sha256 "4705767598300e56d40732e0ae70f43019fea26e537f1b61d7ca5665c01cf121"
      define_method(:install) do
        bin.install "opstea"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/AitorDuran/opstea/releases/download/v0.5.1/opstea_0.5.1_linux_arm64.tar.gz"
      sha256 "d57256368e1f1c98b399cb95601c34cca9bc8e7b2f7fa54d8856a728f300aca1"
      define_method(:install) do
        bin.install "opstea"
      end
    end
  end

  test do
    system "#{bin}/opstea", "--version"
  end
end
